habranalog/accsapp/urls.py
from django.urls import path
from accsapp.views import *
app_name='accsapp'
urlpatterns=[
    path('sign-up/',signup,name='signup'),
    path('sign-in/',signin,name='signin'),
    path('sign-out/',signout,name='signout'),
    path('profile/',profile,name='profile')
]

habranalog/articleapp/urls.py
from django.urls import path
from articleapp.views import *
app_name='articleapp'
urlpatterns=[
    path('',home,
         name='home'),
    path('view-art-<int:art_id>',view_art,name='view_art'),
    path('create-article/',create_article,name='create_article'),
    path('change-article-<int:art_id>/',change_article,name='change_article'),
    path('view-article-<int:art_id>/',view_article,name='view_article'),
    path('delete-article-<int:art_id>/',delete_article,name='delete_article'),
    # path('change-article-<int:art_id>/create-article-block',change_article,name='change_article'),
    # path('change-article-<int:art_id>/change-article-block-<int:art_id>',change_article,name='change_article'),
]

habranalog/habranalog/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('articleapp.urls')),
    path('accs/',include('accsapp.urls')),
    path('main-app',include('mainapp.urls'))
 
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

habranalog/mainapp/urls.py
app_name='mainapp'
urlpatterns = [
    
]

habranalog/accsapp/models.py
from django.db import models

# Create your models here.

habranalog/articleapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Article(models.Model):
    title=models.CharField(max_length=150)
    prememo=models.TextField(null=True,blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='articleapp/images',null=True,blank=True)
    date_published=models.DateField(auto_now_add=True)
    published=models.BooleanField(default=False)
    def __str__(self):
        return str(self.id)+'__'+self.title
    

class ArticlesBlock(models.Model):
    title=models.CharField(max_length=150)
    memo=models.TextField(null=True,blank=True)
    image=models.ImageField(upload_to='articleapp/images',null=True,blank=True)
    date_published=models.DateField(auto_now_add=True)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)+'__'+self.title
    

class Views(models.Model):
    user=models.ForeignKey(User,on_delete=models.PROTECT)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)
    class Meta: 
        unique_together=('user','article',)

habranalog/mainapp/models.py
from django.db import models

# Create your models here.

habranalog/articleapp/forms.py
from articleapp.models import * 
from django.forms import ModelForm

class CreateArticleForm(ModelForm):
    class Meta:
        model=Article
        fields=['title','prememo','image']

habranalog/accsapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from articleapp.models import * 

def signup(request):
    if request.user.is_authenticated:
      return redirect('articleapp:home')
    else:
      if request.method=='GET':
        return render(request,'accsapp/signup.html',{'form':UserCreationForm()})
      else:
        if request.POST['password1']==request.POST['password2']:
            try:
                user=User.objects.create_user(username=request.POST['username'],password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('articleapp:home')
            except IntegrityError:
                return render(request,'accsapp/signup.html',{'form':UserCreationForm(),'error':'такой пользователь уже существует'})
        else:
            return render(request,'accsapp/signup.html',{'form':UserCreationForm(),'error':'пароли не совпадают'})
        

def signin(request):
    if request.user.is_authenticated:
       return redirect('articleapp:home')
    else:
      if request.method=='GET':
        return render(request,'accsapp/signin.html',{'form':AuthenticationForm()})
      else:
        user=authenticate(request,username=request.POST['username'],password=request.POST['password'])
        if user is None:
          return render(request,'accsapp/signin.html',{'form':AuthenticationForm(),'error':'такого пользователя не существует'})
        else:
          login(request,user)
          return redirect('articleapp:home')
  
      

@login_required
def signout(request):
  
    logout(request)
    return redirect('articleapp:home') 


@login_required 
def profile(request):
  publicart=Article.objects.filter(author=request.user,published=True)
  privateart=Article.objects.filter(author=request.user,published=False)
  return render(request,'accsapp/profile.html',context={'publicart':publicart,'privateart':privateart})

habranalog/articleapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from articleapp.models import *
from django.contrib.auth.decorators import login_required
from articleapp.forms import * 
def home(request):
    user_filter_state=request.session.get('user_filter_state','up')
    data=Article.objects.filter(published=True).all().order_by('date_published')
    if request.GET.get('sort_by')=='up':
        request.session['user_filter_state']='up'
        user_filter_state=request.session['user_filter_state']
        data=Article.objects.filter(published=True).all().order_by('date_published')
    elif request.GET.get('sort_by')=='down':
        request.session['user_filter_state']='down'
        user_filter_state= request.session['user_filter_state']
        data=Article.objects.filter(published=True).all().order_by('-date_published')
    return render(request,'articleapp/home.html',{'articles':data,'user_filter_state':user_filter_state})


def view_art(request,art_id):
    viewscount=Views.objects.filter(article=art_id).count()
    data=get_object_or_404(Article,pk=art_id,published=True)
    try:
        v=Views.objects.create(user=request.user,article=data)
    except:
        pass
    blocks=ArticlesBlock.objects.filter(article=art_id)
    return render(request,'articleapp/view_art.html',{'article':data,'blocks':blocks,'viewscount':viewscount})


@login_required
def create_article(request):
    if request.method=='GET':
        return render(request,'articleapp/create_article.html',{'form':CreateArticleForm()})
    else: 
        try:
            form=CreateArticleForm(request.POST,request.FILES)
            newart=form.save(commit=False)
            newart.author=request.user
            form.save()
            return redirect('articleapp:home')
        except ValueError:
            return render(request,'articleapp/create_article.html',{'form':CreateArticleForm(),'error':'неккоректные значения'})

@login_required
def change_article(request,art_id):
    article=get_object_or_404(Article,pk=art_id,author=request.user)
    if request.method=='GET':
          return render(request,'articleapp/change_article.html',{'article':article})
    else: 
        try:
            form=CreateArticleForm(request.POST,request.FILES,instance=article)
            form.save()
            return redirect('articleapp:home')
        except ValueError:
            return render(request,'articleapp/change_article.html',{'error':'неккоректные значения','article':article})


@login_required
def view_article(request,art_id): # переименовать view_art
    article_=get_object_or_404(Article,pk=art_id,author=request.user)
    articleblocks=ArticlesBlock.objects.filter(article=art_id)
    return render(request,'articleapp/view_article.html',{'article':article_,'articleblocks':articleblocks}) 

@login_required
def delete_article(request,art_id):
    article=get_object_or_404(Article,pk=art_id,author=request.user)
    if request.method=='POST':
        article.published=False
        article.save()
        return redirect('articleapp:home')

habranalog/mainapp/views.py
from django.shortcuts import render

# Create your views here.

habranalog/accsapp/templates/accsapp/profile.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h2>Мой профиль </h2>
<h2>Мои статьи </h2>
<h3>Опубликованные</h3>

{% for i in publicart %}
<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">{{ i.title }}</h5>

    <a href="{% url 'articleapp:view_article' i.id %}" class="btn btn-primary">Редактировать</a>
  </div>
</div>
<br>
{% endfor %}
<h3>Неопубликованные</h3>
{% for j in privateart %}
<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">{{ j.title }}</h5>

    <a href="{% url 'articleapp:view_article' j.id %}" class="btn btn-primary">Редактировать</a>
  </div>
</div>
<br>
{% endfor %}
{% endblock %}

habranalog/accsapp/templates/accsapp/signin.html
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="войти">
</form>
<small>{{ error }}</small>

habranalog/accsapp/templates/accsapp/signup.html
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="зарегестрироваться">
</form>
<small>{{ error }}</small>

habranalog/articleapp/templates/articleapp/change_article.html
  <form action="" method="POST" enctype="multipart/form-data"> 
  {% csrf_token %}
    <p>
      <label for="id_title">Title:</label>
      <input type="text" name="title" maxlength="150" required id="id_title" value="{{ article.title }}">
      
      
    </p>
  
    
    <p>
      <label for="id_prememo">Prememo:</label>
      <textarea name="prememo" cols="40" rows="10" id="id_prememo">
        {{ article.prememo }}
  </textarea>
      
      
    </p>
  
    
    <p>
      <label for="id_image">Image:</label>
      <input type="file" name="image" accept="image/*" id="id_image">
      
      
        
      
    </p>
    <input type="submit" value="изменить">
  </form>
  <form action="{% url 'articleapp:delete_article' article.id  %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="удалить"> 
  </form>
<small> {{ error }}</small>

habranalog/articleapp/templates/articleapp/create_article.html
<form action="" method="POST" enctype="multipart/form-data"> 
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="создать">
</form>
<small> {{ error }}</small>

habranalog/articleapp/templates/articleapp/home.html
{% extends 'mainapp/base.html' %}
{% block content %}
<form action="" method="GET">
  <select name="sort_by" id="">
    <option value="up" {% if user_filter_state == 'up' %} selected {% endif %}>по возрастанию </option>
    <option value="down" {% if user_filter_state == 'down' %} selected {% endif %}> по убыванию </option>
  </select>
<input type="submit" value="отфильтровать"> 
</form>
{% autoescape off %}
  {% for i in articles %}
  <h2>
    <a href="{% url 'articleapp:view_art' i.id %}">
      {{ i.title }}
    </a>
   
  </h2>
  <h3>
    {{ i.prememo }} 
  </h3>
  {% if i.image %}
  <img src="  {{ i.image.url }} " alt="" >


  {% endif %}
  {% endfor %}
  {% endautoescape %}
{% endblock %}

habranalog/articleapp/templates/articleapp/view_art.html
{% extends 'mainapp/base.html' %}
{% block content %}

<h2>{{ article.title }}</h2>
{% for i in  blocks %}
<h3>{{ i.title }}</h3>
<p> {{ i.memo  }}</p>

{%  endfor %}
<h4>
  {{ viewscount }}
</h4>

{% endblock %}

habranalog/articleapp/templates/articleapp/view_article.html
{% extends 'mainapp/base.html' %}
{% block content %}

<h3>Статья</h3>

<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">{{ article.title }}</h5>

    <a href="{% url 'articleapp:change_article' article.id %}" class="btn btn-primary">Редактировать</a>
  </div>
</div>
<br>

<h3>Блоки</h3>
{% for j in articleblocks %}
<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">{{ j.title }}</h5>

    <a href="#" class="btn btn-primary">Редактировать</a>
  </div>
</div>
<br>
{% endfor %}
<div class="card w-50">
  <div class="card-body">
   

    <a href="{% url 'articleapp:create_article' %}" class="btn btn-primary">Добавить</a>
  </div>
</div>
{% endblock %}

habranalog/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HabrAnalog</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
    <a class="navbar-brand" href="{% url 'articleapp:home'%}">HabrAnalog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Домой <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'articleapp:create_article' %}" >Добавить статью</a>
        </li>

      
     
        </li>
     
      </ul>
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'accsapp:profile' %}">   {{ user.username }}</a>
     
  
    
      <form class="form-inline my-2 my-lg-0" action="{% url 'accsapp:signout' %}">
        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">выйти</button>
      </form>
      {% else %}
      <a class="nav-link" href="{% url 'accsapp:signin' %}">войти</a>
      <a class="nav-link" href="{% url 'accsapp:signup' %}"> зарегестрироваться </a>
      {% endif %}
    
    </div>
  </div>
  </nav>
  <div class="container">
  {% block content %}



  {% endblock %}
</div>
</body>
</html>